### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by wab030** [viniciuscrw/cestas-cooperflora-rn#162]
Erro ocorre quando uma nova entrega é cadastrada. 

PayloadTooLargeError: request entity too large
    at readStream (/home/bordi/projects/cestas-cooperflora-rn/node_modules/raw-body/index.js:155:17)
    at getRawBody (/home/bordi/projects/cestas-cooperflora-rn/node_modules/raw-body/index.js:108:12)
    at read (/home/bordi/projects/cestas-cooperflora-rn/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/home/bordi/projects/cestas-cooperflora-rn/node_modules/body-parser/lib/types/json.js:135:5)
    at call (/home/bordi/projects/cestas-cooperflora-rn/node_modules/connect/index.js:239:7)
    at next (/home/bordi/projects/cestas-cooperflora-rn/node_modules/connect/index.js:183:5)
    at remoteDevtoolsCorsMiddleware (/home/bordi/projects/cestas-cooperflora-rn/node_modules/@expo/dev-server/build/middleware/remoteDevtoolsCorsMiddleware.js:27:5)
    at call (/home/bordi/projects/cestas-cooperflora-rn/node_modules/connect/index.js:239:7)
    at next (/home/bordi/projects/cestas-cooperflora-rn/node_modules/connect/index.js:183:5)
    at serveStatic (/home/bordi/projects/cestas-cooperflora-rn/node_modules/serve-static/index.js:75:16)

**Comment by wab030** [comment]
Resolvido.
